jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1          # tu región
          aws-access-key-id:     ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY }}

      # ahora cualquier comando aws-cli funciona:
      - run: aws sts get-caller-identity
