.github/workflows/train-embeddings.yml
# .github/workflows/train-embeddings.yml
name: Daily Face-Embedding Training

on:
  schedule:
    # A las 02:00 hora de Bogotá (UTC-5) → 07:00 UTC
    - cron: '0 7 * * *'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run embedding training script
        run: |
          python facialRecognition/entrenamiento_guardado.py
